language: node_js
sudo: false
os: linux
dist: bionic

nodejs:
  - 14

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - boost1.67
    - env: COMPILER=g++-6 BUILD=Release STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - boost1.67


services:
  - redis

cache:
  npm

matrix:
  fast_finish: true

  include:
    

before_install:
    - "npm install -g npm@latest"

install:
    - npm install
    - cp defaults/config.travis.json config.json

script:
  - npm run tests

notifications:
  email: false
