language: node_js
sudo: false
os: linux
dist: bionic

nodejs:
  - 14

matrix:
  fast_finish: true
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
    

services:
  - redis

cache: npm  

before_install:
    - "npm install -g npm@latest"

install:
    - npm install
    - cp defaults/config.travis.json config.json

script:
  - npm run tests

notifications:
  email: false
